### ISSUE TITLE
[Front-end] Add Security Headers

### ISSUE THREAD

**Issue by heitorlessa** [aws-samples/aws-serverless-airline-booking#70]
Security headers can be applied at CI level: https://docs.aws.amazon.com/en_pv/amplify/latest/userguide/custom-headers.html#example-security-headers

**Comment by heitorlessa** [comment]
Current working implementation in stage env - CSP is tricky because we can't a custom domain so it's acting mostly as an example, but not the most secure on connect, etc.

```
  customHeaders:
  - pattern: "**/*"
    headers: # https://infosec.mozilla.org/guidelines/web_security
      - key: "Strict-Transport-Security"
        value: "max-age=31536000; includeSubDomains"
      - key: "X-Content-Type-Options"
        value: "nosniff"
      - key: "X-XSS-Protection"
        value: "1; mode=block"
      - key: "X-Frame-Options"
        value: "DENY"
      - key: "Referrer-Policy"
        value: "same-origin"
      - key: "Feature-Policy"
        value: "microphone 'none'; camera 'none'; notifications 'self'"
      - key: "Content-Security-Policy"
        value: "'default-src 'none'; connect-src https://*.amazonaws.com; font-src 'self' https://fonts.gstatic.com; frame-src https://js.stripe.com; img-src 'self'; script-src 'self' 'unsafe-eval' https://js.stripe.com/v3/; style-src 'self' https://fonts.googleapis.com/css?family=Raleway 'unsafe-inline' https://fonts.googleapis.com'"
```
